# Generated by Django 5.1.2 on 2024-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prod',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prod',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='prod',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
